# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/23a8c46d-b26f-4d98-bedd-d659b0c25413";
    fsType = "btrfs";
    options = [
      "subvol=@nixos"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" =
    #  { device = "/dev/disk/by-uuid/23a8c46d-b26f-4d98-bedd-d659b0c25413";
    #    fsType = "btrfs";
    #    options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    #  };

    {
      device = "/dev/disk/by-uuid/99049b36-481b-42a6-abc8-a77008840a18";
      #  { device = "/dev/disk/by-uuid/ac1b57a3-e188-49ec-9cd7-0ecdf5dd77ed";
      fsType = "bcachefs";
    };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/23a8c46d-b26f-4d98-bedd-d659b0c25413";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2C93-0F4A";
    fsType = "vfat";
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/DA0294B802949AD9";
    fsType = "ntfs";
  };

  fileSystems."/mnt/segate4t" = {
    device = "/dev/disk/by-uuid/3034D2CA34D29268";
    fsType = "ntfs";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
